### ISSUE TITLE
none ASCII

### ISSUE THREAD

**Issue by kh0fo** [nulldigit90/TechBot#2]
EDIT: The bot crashes when a none ascii is entered by any user wether or not the after a command 

When a command !convert for example is followed by non ASCII characters (π) for example, the bot disconnects:
<khofo> !convert π
(*)TechBot_Test has quit (Client exited)

Error: 
Traceback (most recent call last):
  File "TechBot.py", line 88, in <module>
    bot.main()
  File "TechBot.py", line 70, in main
    fulldata = self.recvData()
  File "/home/khofo/py-scripts/TechBot/ircbot/irc.py", line 82, in recvData
    data = self.sock.recv(1024).decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 72: ordinal not in range(128)

**Comment by techb** [comment]
It has been fixed. irc.py now uses utf-8
